apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: stock-feed
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/shivanetd/stock-feed
              tag: v1
            env:
              - name: PORT
                value: &port 8080
              - name: MONGODB_URL
                valueFrom:
                  secretKeyRef:
                    name: stock-secret
                    key: mongo-url
              - name: Alpaca_Key
                valueFrom:
                  secretKeyRef:
                    name: stock-secret
                    key: alpaca-key
              - name: Alpaca_Secret
                valueFrom:
                  secretKeyRef:
                    name: stock-secret
                    key: alpaca-secret
            resources:
              requests:
                memory: 250M
              limits:
                memory: 500M
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
    
