---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app stock-feed-app
  namespace: flux-system
spec:
  targetNamespace: hman-app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/hman-app/stock-feed-app/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 5m
  retryInterval: 1m
  timeout: 5m
