apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:6RcgMCaqM1jDJ7WKtCPowKz7zeKFJArF5DbjO2OseIsjdK0oYj60vg==,iv:HBFGjyqIcLdt+8KREIDQ06HQomnfE1BpbMhcui/nZHc=,tag:5q8nhdd+7MpTfjzAtFgq6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age178cr0cw9urqdwq4f9w0jnmzryp000tzztcz8yjnk8h2w2dc8ls9s93tmwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT0U4amFpc2I2WndjZ2pT
            S1lHL21DV1NyTStVNm9mdEt2OTFjYTJDN3owCkVoNlBJMEJDNGVtUEt4a1M1ZmU1
            SklvMXhndEo0RGQyT1RNS3dydDRyd28KLS0tIFloQmtmby9CbUpGbFRqNittMjhZ
            aFZrLzdubS8zdDNYSDc4MU9yQmRTRkkKkIQBcMriiFJXTaZi1XXi3LSvBWseve9F
            yeWJfDV0deaGjpvW6fONfinUrro0j5tEY++AjKpoNB6hUFAqmISscw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-29T00:26:36Z"
    mac: ENC[AES256_GCM,data:CjAu9Zw+pvFy/vpzEQWUu7aX3q4m1ieIhiypTX02iuAjX80ubg8J0apk9ut6303vnXL5tYHEbOxaB8ZVVVVX11yxv5AOIwOXQNEwDfAvs+ydNB2vsWqFAsr/Tbbi3NVCsiygvMNZR1ZZRARKN8cCUjHKNJ7J07TTqApiLtws7wo=,iv:CpuYhuwZn6eWassa9skMFxT9mkXvKmExAnPunim0SPk=,tag:DkULZPoZngCrKxTC2y4HJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
