apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:S97RJwOSrce2pPS6TH98ezwocWuDf9bYOfTcxHz+BabCSEQZSuCsmA==,iv:h2SbH+eAXGvM2C17Uj+bZSoKcqBtgGkfDBe26mwWGrE=,tag:MA33F+0zb6sofHV3zCXmXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age178cr0cw9urqdwq4f9w0jnmzryp000tzztcz8yjnk8h2w2dc8ls9s93tmwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Q1dxekh0SVFtYy9KazBp
            TGRMbXpraGJpRURaVVdkNmRSaENTY2I4K1RVCnF2S2dXQ1E5UlFKaGFCTUh4NDJk
            dG1aVld0NnJQcGEzcGF4Q29ObUJpNFEKLS0tIE8raDBCajZ6TjJaQkNRbXN4K2po
            VWFWQmNyNE8vZGZ1S1p6aWNvZ1BZZnMKIdI+/P9ZzZwAeAql98qOQilqIHNDFqPG
            zMhE9YwbieXUGcVECM1ejFzKuFEN7YaIaICA7j16f1WoCNL+ofjvTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T16:50:49Z"
    mac: ENC[AES256_GCM,data:dUqzhdg2eczZ+u6FwpwYrg/12b7W7rHECxdZosQb7+uhBP6ec9NYQkPr4U1ekyuxkNepF9eGuSIDEwaG4hn3210sMSpz6q3KaACMnFk2i//db6DIZB+BbW7oO1aFM/tizUYuJp0py/9HMzO1xYR/8KQ2zP8nL+7awngsFUmP7W8=,iv:VgsWTnMuoW4Pu534oNW1QUnTON4jZRUjvj9kEDDnVKQ=,tag:Cl09nazXfx0swZxZlEFVTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
